spring:
  # jsp 관련 설정
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  # oracle 관련 설정
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: finalpro
    password: 1234

# mybatis 관련 설정
mybatis:
  mapper-locations: /mappers/*.xml # mapper.xml 위치 설정
  type-aliases-package:

  configuration:
    jdbc-type-for-null: varchar # # ""값 null 처리